import AuthButton from "@sections/AuthButton";
import { NextPageWithLayout } from "@types";
import Head from "next/head";
import * as styles from "./styles";

const AuthPage: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <styles.Main>
        <AuthButton />
      </styles.Main>
    </div>
  );
};

export default AuthPage;
