import AuthButton from "@components/AuthButton";
import MessageScreen from "@components/MessageScreen";
import Head from "next/head";
import { trpc } from "@services/trpc";
import { useUser } from "@auth0/nextjs-auth0";
import { Button, HighlightedText, Paragraph, Subtitle } from "@styles/common";
import * as styles from "./index.styles";
import Spinner from "@components/Icons/Spinner";
import { formatDateLong } from "@utils/date";
import { NextPageWithLayout } from "@types";
import UsersList from "@components/Lists/UsersList";

const Home: NextPageWithLayout = () => {
  const utils = trpc.useContext();
  const { user, error, isLoading } = useUser();
  const getAllUsers = trpc.useQuery(["users.all"]);

  const addUser = trpc.useMutation("users.add", {
    async onSuccess(newUser) {
      return await utils.invalidateQueries(["users.all"]);
    },
  });

  if (getAllUsers.status === "loading")
    return <MessageScreen message='loading..' />;

  if (getAllUsers.status === "error")
    return <MessageScreen message={getAllUsers.error.message} />;

  const addMeHandler = async () => {
    if (user) {
      return addUser.mutate({
        name: user.name as string,
        email: user.email as string,
        picture: user.picture as string,
      });
    }
  };

  if (!getAllUsers.data) return <MessageScreen message='no users' />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <styles.Main>
        <styles.Title>Home page</styles.Title>
        {user && (
          <Button onClick={addMeHandler}>
            {addUser.isLoading && <Spinner />}
            Add me
          </Button>
        )}
        <UsersList users={getAllUsers.data} />
        <AuthButton />
      </styles.Main>
    </div>
  );
};

export default Home;
