import AuthButton from "@components/AuthButton";
import MessageScreen from "@components/MessageScreen";
import Head from "next/head";
import { trpc } from "@services/trpc";
import { useUser } from "@auth0/nextjs-auth0";
import { Button, HighlightedText, Paragraph, Subtitle } from "@styles/common";
import * as styles from "./index.styles";
import Spinner from "@components/Icons/Spinner";
import { formatDateLong } from "@utils/date";
import { NextPageWithLayout } from "@types";
import ProjectsList from "@components/Lists/ProjectsList";

const Projects: NextPageWithLayout = () => {
  const utils = trpc.useContext();
  const { user } = useUser();
  const getCurrentUser = trpc.useQuery([
    "users.oneByEmail",
    { email: user?.email as string },
  ]);
  const getAllProjects = trpc.useQuery(["projects.all"]);

  const addProject = trpc.useMutation("projects.add", {
    async onSuccess(newUser) {
      return await utils.invalidateQueries(["projects.all"]);
    },
  });

  if (getAllProjects.status === "loading")
    return <MessageScreen message='loading..' />;

  if (getAllProjects.status === "error")
    return <MessageScreen message={getAllProjects.error.message} />;

  const addProjectHandler = async () => {
    if (getCurrentUser.data) {
      return await addProject.mutate({
        name: "Template text",
        description: "Template text description.",
        ownerId: getCurrentUser.data.id as string,
      });
    }
  };

  if (!getAllProjects.data) return <MessageScreen message='no projects' />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <styles.Main>
        <styles.Title>Projects page</styles.Title>
        {user && (
          <Button onClick={addProjectHandler}>
            {addProject.isLoading && <Spinner />}
            Add new project
          </Button>
        )}
        <ProjectsList projects={getAllProjects.data} />
        <AuthButton />
      </styles.Main>
    </div>
  );
};

export default Projects;
