import AuthButton from "@components/AuthButton";
import Head from "next/head";
import { trpc } from "@services/trpc";
import { Button } from "@styles/common";
import * as styles from "./styles";
import Spinner from "@components/Icons/Spinner";
import { NextPageWithLayout } from "@types";
import ProjectsList from "@components/Lists/ProjectsList";
import {
  CurrentUserContextInterface,
  CurrentUserContext,
} from "@components/Providers/currentUser";
import { useContext, useState } from "react";
import Modal from "@components/hocs/Modal";
import ManageProjectForm from "@components/forms/ManageProjectForm";
import { Project } from "@prisma/client";
import { IProjectFormValues } from "@components/forms/ManageProjectForm/helper";

const Projects: NextPageWithLayout = () => {
  const [openModal, setOpenModal] = useState(false);
  const utils = trpc.useContext();
  const { currentUser } =
    useContext<CurrentUserContextInterface>(CurrentUserContext);

  const addProject = trpc.useMutation("projects.add", {
    async onSuccess() {
      return await utils.invalidateQueries(["projects.all"]);
    },
  });

  const addProjectHandler = async (p: IProjectFormValues) => {
    if (currentUser) {
      try {
        await addProject.mutateAsync({
          name: p.name,
          description: p.description,
          ownerId: currentUser.id as string,
        });
      } catch (e) {}
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <styles.Main>
        <styles.Title>Projects page</styles.Title>
        {currentUser && (
          <>
            <Modal
              actionButton={
                <Button color='green' onClick={() => setOpenModal(true)}>
                  {addProject.isLoading && <Spinner />}
                  Add new project
                </Button>
              }
              show={openModal}
            >
              <ManageProjectForm
                isSubmitting={addProject.isLoading}
                mode='create'
                onClose={() => setOpenModal(false)}
                onSubmitAsync={addProjectHandler}
              />
            </Modal>
            <ProjectsList ownerId={currentUser.id} />
          </>
        )}
        <AuthButton />
      </styles.Main>
    </div>
  );
};

export default Projects;
